# Generated by Django 5.2.1 on 2025-07-09 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_museu_delete_itemmuseu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("palpite", "Palpite"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
