# Generated by Django 5.2.1 on 2025-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_historico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("idade", models.IntegerField()),
                ("posicao", models.CharField(max_length=255)),
            ],
        ),
    ]
