# Generated by Django 5.2.1 on 2025-07-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_jogador"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="sobrenome",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
